services:
  - type: web
    name: campus-booking-system
    runtime: java
    runtimeVersion: "17"
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/booking-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: "8081"
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
